version: "2.1"

services:

  qbittorrent:

    image: lscr.io/linuxserver/qbittorrent:latest

    container_name: qbittorrent

    environment:

      - PUID=1000

      - PGID=1000

      - TZ=America/Sao_Paulo

      - WEBUI_PORT=8089

    volumes:

      - /dados/qb-nox/config:/config

      - /dados/qb-nox/downloads:/downloads

    ports:

      - 8089:8089

      - 6881:6881

      - 6881:6881/udp

    restart: unless-stopped
