version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/ #optional
      - USER=user #optional
      - PASS=password #optional
    volumes:
      - /home/felipe/.transmission/data:/config
      - /dados/transmission:/downloads
      - /dados/transmission:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
